// Visual templates for the 1080x1920 reel stage.
// Each entry is a set of CSS custom properties plus the animated backdrop it uses.

export const TEMPLATES = [
  {
    id: 'neon',
    name: 'Neon Arcade',
    tag: 'Max energy',
    blurb: 'Electric cyan and magenta on deep violet. Best scroll-stopper.',
    backdrop: 'neon',
    vars: {
      '--t-bg': '#0a0320',
      '--t-bg2': '#1d0748',
      '--t-ink': '#ffffff',
      '--t-muted': '#a99ad9',
      '--t-card': 'rgba(255,255,255,.07)',
      '--t-card-line': 'rgba(255,255,255,.18)',
      '--t-accent': '#00e5ff',
      '--t-accent2': '#ff2d95',
      '--t-correct': '#2bff88',
      '--t-warn': '#ff3b6b',
      '--t-badge': 'linear-gradient(140deg,#00e5ff,#7c4dff)',
      '--t-glow': '0 0 42px rgba(0,229,255,.5)',
      '--t-title': "'Outfit'",
    },
  },
  {
    id: 'sunset',
    name: 'Sunset Pop',
    tag: 'Warm + friendly',
    blurb: 'Coral, tangerine and hot pink. Reads great on small screens.',
    backdrop: 'sunset',
    vars: {
      '--t-bg': '#2a0a3d',
      '--t-bg2': '#7a1148',
      '--t-ink': '#fff6ef',
      '--t-muted': '#f2b9a6',
      '--t-card': 'rgba(255,255,255,.12)',
      '--t-card-line': 'rgba(255,225,205,.28)',
      '--t-accent': '#ffb020',
      '--t-accent2': '#ff4d6d',
      '--t-correct': '#4df0a6',
      '--t-warn': '#ff6b3d',
      '--t-badge': 'linear-gradient(140deg,#ff8a3d,#ff2d6f)',
      '--t-glow': '0 0 42px rgba(255,140,60,.5)',
      '--t-title': "'Outfit'",
    },
  },
  {
    id: 'cyber',
    name: 'Cyber Grid',
    tag: 'Techy + bold',
    blurb: 'Perspective grid with acid-lime accents on midnight navy.',
    backdrop: 'cyber',
    vars: {
      '--t-bg': '#040b16',
      '--t-bg2': '#07203a',
      '--t-ink': '#eafcff',
      '--t-muted': '#7ba7c4',
      '--t-card': 'rgba(10,40,64,.55)',
      '--t-card-line': 'rgba(126,255,158,.26)',
      '--t-accent': '#c6ff3d',
      '--t-accent2': '#00c2ff',
      '--t-correct': '#7dff9f',
      '--t-warn': '#ff5252',
      '--t-badge': 'linear-gradient(140deg,#c6ff3d,#00c2ff)',
      '--t-glow': '0 0 40px rgba(198,255,61,.42)',
      '--t-title': "'Space Grotesk'",
    },
  },
  {
    id: 'bubble',
    name: 'Bubblegum',
    tag: 'Soft + cute',
    blurb: 'Candy pastels and floating bubbles. Great for light niches.',
    backdrop: 'bubble',
    vars: {
      '--t-bg': '#ffe3f1',
      '--t-bg2': '#dbe4ff',
      '--t-ink': '#3b1b52',
      '--t-muted': '#8a6ba3',
      '--t-card': 'rgba(255,255,255,.78)',
      '--t-card-line': 'rgba(120,70,160,.16)',
      '--t-accent': '#ff5fa8',
      '--t-accent2': '#7c6bff',
      '--t-correct': '#12b981',
      '--t-warn': '#ff4d6d',
      '--t-badge': 'linear-gradient(140deg,#ff5fa8,#7c6bff)',
      '--t-glow': '0 0 36px rgba(255,95,168,.35)',
      '--t-title': "'Outfit'",
    },
  },
  {
    id: 'luxe',
    name: 'Gold Luxe',
    tag: 'Premium look',
    blurb: 'Matte black with shimmering gold. Feels expensive.',
    backdrop: 'luxe',
    vars: {
      '--t-bg': '#08080a',
      '--t-bg2': '#1a1509',
      '--t-ink': '#fdf6e3',
      '--t-muted': '#a3966f',
      '--t-card': 'rgba(255,240,200,.06)',
      '--t-card-line': 'rgba(226,190,110,.3)',
      '--t-accent': '#f0c65a',
      '--t-accent2': '#e08b3c',
      '--t-correct': '#5fe0a0',
      '--t-warn': '#ff6b4d',
      '--t-badge': 'linear-gradient(140deg,#f7d97a,#c8912e)',
      '--t-glow': '0 0 40px rgba(240,198,90,.4)',
      '--t-title': "'Space Grotesk'",
    },
  },
  {
    id: 'aurora',
    name: 'Aurora Flow',
    tag: 'Calm + hypnotic',
    blurb: 'Slow drifting ribbons of mint and indigo. Very watchable.',
    backdrop: 'aurora',
    vars: {
      '--t-bg': '#04121a',
      '--t-bg2': '#0b2b3a',
      '--t-ink': '#eafff8',
      '--t-muted': '#82b8b5',
      '--t-card': 'rgba(255,255,255,.08)',
      '--t-card-line': 'rgba(160,255,225,.2)',
      '--t-accent': '#4df0c4',
      '--t-accent2': '#6f8cff',
      '--t-correct': '#4df0a6',
      '--t-warn': '#ff7a5c',
      '--t-badge': 'linear-gradient(140deg,#4df0c4,#6f8cff)',
      '--t-glow': '0 0 40px rgba(77,240,196,.4)',
      '--t-title': "'Outfit'",
    },
  },
]

export const DEFAULT_TEMPLATE = TEMPLATES[0].id

export function getTemplate(id) {
  return TEMPLATES.find((item) => item.id === id) || TEMPLATES[0]
}
